<?php

use Illuminate\Database\Seeder;

class TextblocksTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$textblocks = [
			[
				'key' => 'terms_and_conditions',
				'text' => 'The TERMS AND CONDITIONS set forth below are associated with the MEMBERSHIP AGREEMENT (the "Agreement") that has been entered into by and between the member listed in the Agreement (the "Member") and District Cowork Nomad LLC ("District"). This document in conjunction with the Agreement constitute the entire agreement between the Member and District and explains the details of your membership.

1. Services. Subject to these terms and conditions and during the normal operating hours established by District, District agrees to provide the Member with (i) access to District’s Facility and the office space described in the Membership Details, (ii) furnishings for the office space of the quantity and quality typically provided in the District location, (iii) heat and air-conditioning in the office space during regular Business Hours on regular Business Days; (iv) access to and use of the shared wireless internet connection, (v) access to and use of the Member Portal, (vi) use of the printers, copiers and scanners subject to availability and consistent with the pricing then in effect, (vii) access to and use of the conference rooms located in the Facility subject to availability and consistent with the pricing then in effect; (viii) acceptance of mail and deliveries at the Facility on the Member’s behalf, and the Member hereby appoints District as its agent to receive such mail and deliveries during Business Hours, and (ix) opportunity to attend events, benefits and promotions that are open to Members. Member acknowledges that printer/copier and conference room credits expire every month and usage in excess of credits is subject to overage fees as listed in the Member Portal.

Regular Business Hours are generally from 9:00 a.m. to 6:00 p.m. with the exception of days prior to U.S. federal holidays, when our regular business hours end at approximately 1:00 p.m. "Business Days" are all weekdays, except U.S. federal holidays and up to four other days of which District will furnish. Office level Members have access to their private office from 8 a.m. to 11:00 p.m on weekdays and 10 a.m. to 6 p.m. on weekends. District will, on a best efforts basis, provide access to the space beyond these times on a case by case bases if requested in advance by Member. Member acknowledges that District reserves the right to hold private functions in the Gallery and Canteen area anytime on weekends and on weekdays prior to 9 a.m and post 6:00 p.m. Gallery and NoMad members acknowledge that their membership is limited to weekdays from 9 a.m. to 6 p.m. if the Gallery is booked for an event.

District is entitled to access Member office space, with or without notice, for maintenance, safety or emergency purposes. During these times, District may temporarily move furniture contained in the office space. District reserves the right to move or alter the office space. District may modify or reduce the Services as listed herein at any time with prior notice. The Services may be provided by District, an affiliate or a third party. District has the right to amend the Business Hours at any time and will provide notice of such change via email to Member address set forth in Member Details.

2. Members List; Guests. The Member acknowledges that it is responsible for providing accurate information to District regarding the employees or contractors of the Member listed in the Members List which desire to use the Facility on a regular basis. As part of the membership fee, the Member is entitled to a set number of individual memberships matching the Capacity of the office space assigned in the Membership Details. Additional members may be granted access for a non-prorated fee of $350.00 per month subject to approval by District. Whether or not Member has paid for additional individuals to the Members List, no more than stated Capacity is permitted to work at District at any given time. The Members’ office space may not be regularly accessed by individuals not on the Members List. A copy of a photo ID is required for each Individual on the Members List in order to obtain a key and keycard access to the office space. Member agrees to promptly inform District of any changes to the individuals named on the Members List before such changes take effect. The Member agrees to email District, at the address specified in this agreement, the name(s) and email address(es) of the departing and new member(s) and the effective date of this change.

The initial Members List shall be furnished to District prior to move-in or no later than 5 days after signing this agreement. District reserves the right to perform a background check on any prospective or existing individual on the Members List and decline or terminate access to any individual based on the results of such check. The Member is responsible for maintaining the accuracy of the names of the Members on the Members List. Only those individuals set forth on the Members List will be granted passcards. District reserves the right to limit the number of additional access cards issued to the Member, and all individuals using the Facility at the Member’s invitation or using any access card issued pursuant to this Agreement shall be subject to the terms and conditions hereof. All guests and invitees shall be registered with District prior to entering the Facility. The Member remains responsible for any charges, costs or liabilities incurred hereunder by any such individual.

3. Fees/Security Deposit. Upon submitting a completed signed agreement, the Member shall be obligated to pay the non-refundable Commitment Fee and set-up fee described in the Membership Details. This agreement will be effective only upon District’s receipt of the signed and completed agreement and the payment of these fees. On the start date, the commitment fee will convert into a security deposit, provided however that the security deposit is not intended to serve as a reserve from which fees are to be paid. The security deposit will be returned to the Member not later than forty five (45) days following the termination of this Agreement, provided that the Member has completely satisfied all obligations hereunder and has returned all District access cards/keys. District shall have no duty to maintain the Security Deposit in an escrow or interest bearing account and such funds will be available for use by District for the duration of the Member’s Membership as provided herein. Member acknowledges that Member is not entitled to any interest on the Security Deposit. If Member wishes to voluntarily change its Membership Level to one(s) carrying higher monthly fees, Member shall deposit with District such additional funds (to be a part of the Security Deposit) in an amount necessary so that the Security Deposit shall at all times be equal to one-and-one-half (1.5) month’s Membership Fee by check or two (2) months by card.

During the term, District will process payment for the Monthly Membership Fee and other charges and fees incurred hereunder on or about the 5th day of each month. The Monthly membership fee covers only the number of members specified or approved by District. In the event that the Member requires use of the facilities by additional individuals above the Capacity listed in Membership Details, additional charges or an increased monthly membership fee will be incurred. The Member is responsible for all charges incurred in accordance with District’s fee schedules listed in the Membership Details and updated on the Member Portal. The full fee schedule is available for review on the Member Portal.

If payment for the monthly membership fee or other charges due is not made by the 5th day of the month, the Member will be responsible for a late fee in the amount of 10% of the overdue amount. District may withhold services or terminate this Agreement if any fees remain outstanding after three (3) weeks or if the Member otherwise does not comply with the terms and conditions of this Agreement. The membership fee is subject to annual increases every year during the term of this agreement.

Fees for overages for printouts/copies and conference room credits are subject to increase from time to time. District will notify Member at least sixty (60) days prior to these increases and post the updated fees on the Member Portal.

4. Form of Payment. The Member shall pay all amounts due hereunder by direct withdrawal from its bank account or by credit card. If the Member elects to pay via direct withdrawal, it agrees to maintain a current voided check with District, maintain sufficient funds in the account to pay amounts incurred hereunder and to inform District promptly of any changes to the account. If the Member elects to pay via credit card, it agrees to inform District promptly of any changes to the account and to replace the card upon expiration. Changes to a member’s form of payment may result in an additional security deposit. Changes to payment method will not be accepted in the last fifteen (15) days of the calendar month. If payment via credit card fails for any reason, District may require the Member to make payments via direct withdrawal plus a $50 fee per failed attempt. Upon receipt of funds, District will apply funds first to any balances in arrears and to the earliest month first, and thereafter to any current charges due. Payment by credit card or Paypal shall be subject to a 3.0% fee on the amount charged, at this time.

5. Term and Termination. This Agreement will be effective when signed by both parties and the Member has paid the fees due upon execution hereof, including the set up and commitment fee. Each membership will begin on the Start Date identified in the Membership Details with the monthly payment due (or, with respect to memberships added after the commencement of the term, upon addition of such individual to the Members List of authorized users). Each membership will terminate upon the earlier of the termination of this Agreement, the Member’s removal of an individual from the Members List of authorized users, or District’s notification that a user has violated this Agreement or its rules and regulations regarding use of the Facility. If the Start Date is a Business Day, the Member will be entitled to move into the office space on the Start Date. If the Start Date is not a Business Day, the Member will be entitled to move into the office space on the first Business Day after the Start Date no earlier than 11 a.m.

Following the Commitment Period outlined in the Membership Agreement, the Member may terminate this Agreement by providing written notice to District at least sixty (60) days prior to the termination, which shall become effective the last business day of the calendar month following the Member’s written notice. Member agrees to specify only the last business day of the calendar month as the termination date and will not be entitled to pro ration with respect to such last month’s membership fee. For example, if Member delivers a 60-day termination notice on March 14 (or anytime between March 1st-March 31st), the termination will not be effective until May 31. This paragraph also applies to changes of office space within Districts available spaces. On such last business day, Member must vacate the office space no later than 4:00 p.m.

District may terminate this Agreement immediately upon a breach of this Agreement by the Member or individuals in the Members List or upon a loss or modification of District’s right to operate the Facility. District may terminate the membership at any other time with or without reason by providing thirty (30) days written notice. Notwithstanding any termination of this Agreement, the Member shall remain liable for amounts incurred prior to the date of termination.

Prior to termination of this Agreement, the Member shall immediately remove all of its personal property (and that of any of its guests or individuals from the Members List) from the Facility. After providing reasonable notice to the Member, District shall be entitled to dispose of any property remaining in the Facility after the termination hereof, and the Member waives any claims or demands regarding such property. The Member shall be responsible for any fees incurred in connection with such removal and disposal. Following the termination of this agreement we will not forward or hold mail or other packages delivered to District.

6. Lack of Space; Effect of Termination. In the event that District is unable to make sufficient office space available to the Member on the Start Date, the Member shall not be liable to make payments of the monthly membership fee until the space is made available to the Member. District shall not otherwise be liable to the Member in any way on account of its inability to make such space available nor should it effect the validity of this agreement. However, if the office space is not available within fifteen (15) days of the Start Date, the Member may terminate this agreement by providing written notice prior to the office space being made available. If Member terminates agreement under this provision, District will all fees received from Member.

7. Changes to Signing Member. The Member signing this agreement has the sole authority to make changes to or terminate this agreement on behalf of its Company and its named Individuals on the Members List. However, an Executive Officer of the Company will have the authority to override the request of the Member, provided that we receive such a request within 24 hours following the Member’s. An executive officer of the Company will also have the authority to remove or replace the individuals serving as the Signing Member. District will rely on communications to and from the Signing Member as notice to and from the Company. We reserve the right to request reasonable information that an individual claiming to be an executive officer of the Company is indeed accurate.

8. House Rules. The Member agrees that: (i) keys and access cards to the building or the Facility shall remain the property of District, and the Member shall safeguard District’s property and be responsible for replacing it in the event of loss, theft or damage; (ii) the Member shall promptly notify District of any changes in contact or payment information; (iii) the Member shall be responsible for reading emails from District sent to the email address listed in the Membership Details and reviewing the Member Portal for updates, changes or modifications to the services offered at the Facility or the fees chargeable in connection therewith; (iv) the Facility may be regularly recorded using video cameras for security reasons; (v) District may disclose information about the Member as necessary to satisfy any applicable law, regulation, legal process or governmental request; (vi) District may amend, add or delete rules and regulations, fees and Services relating to the Facility (which are available for review on the Member Portal) at any time and the Member will be responsible for compliance therewith; (vii) Member acknowledge that the office space has a limited capacity. Whether or not Member has paid for additional members to the Members List, no more than that capacity is permitted to work at District at any given time. The capacity of the office space is in the Membership Details section; and (viii) common spaces are to be enjoyed by our members and guests, for temporary use and not as a place for continuous, everyday work. The Member agrees that it shall not: (i) perform any activity that is reasonably likely to be disruptive or dangerous to other members, their guests or their property; (ii) use the Facility to conduct any illegal activities or activities that are generally regarded as offensive; (iii) attach or affix any items to the walls, install antennas, telecommunications lines or devices or bring additional furniture into the Facility with the prior written approval of District; (iv) take or copy information belonging to other members or their guests; (v) use the Facility to conduct retail or medical activities or otherwise involving frequent visits by members of the public; (vi) make copies of any keys or other means of entry to the Facility or lend any keys or access cards to any third party; (vii) allow any guests to enter the Facility without registering such guests; (viii) bring any weapons into the Facility or upload/download any viruses to the network or (ix) use the name "District Cowork" or use pictures or illustrations of the Premises in any advertising, publicity or other purpose, without our prior written consent;.

The Member acknowledges that notwithstanding these rules, District does not control and is not responsible for the actions of other members. If a dispute arises between members or their guests or invitees, District shall have no responsibility to participate, mediate or indemnify any party.

9. Limitations of Liability; Indemnification. To the fullest extent permitted by law, the Member and each of its employees, agents and invitees, waive any and all claims and rights against District and its affiliates, and each of their members, assignees, officers and directors arising from injury to or damage to, or destruction, theft or loss of property or person. District and its affiliates shall not be liable under any cause of action for any indirect, special, incidental, consequential or punitive damages, including loss of profits or business interruption. The aggregate monetary liability of District and its affiliates to the Member and each of its employees, agents and invitees for any reason and for all causes of action, shall not exceed the total fees paid to District hereunder.

The Member acknowledges that it is responsible to maintain, at its own expense, personal property insurance and commercial general liability insurance covering itself and its employees, agents and invitees for property loss and damage, personal injury and/or loss of use (or prevention of access to) the Facility in amounts sufficient to protect the Member’s business. The Member agrees to provide proof of such coverage upon District’s request, and to cause District and the landlord to be named as additional insureds on any such policies of insurance. Member agrees to provide proof of insurance upon District’s request. Member agrees to provide proof of insurance to District upon entering this agreement.  Proof of insurance, with District and landlord named as additional insureds, will be kept on file and reviewed by District\'s risk managers (Breier Group Concepts, Inc. or any other risk manager hired by District) for compliance.  District’s risk managers will review proof of insurance and will counsel and/or discuss with members when necessary.  In such cases, District’s risk managers will provide compliance recommendations and assist in securing necessary coverages and services on behalf of member so that the member is in compliance with the terms of this provision #10. Members are under no obligation to utilize the services of District\'s risk managers for the securing of necessary coverages but are, nonetheless, required to provide proof of coverage thereof.  Failure to comply with the terms of this provision will provide cause for District’s risk managers to recommend terminating this agreement, per section #5. Term and Termination.

The Member hereby agrees to defend, indemnify and hold harmless District and its affiliates from any against any and all claims, liabilities and expenses, including reasonable attorneys’ fees, resulting from any breach of this Agreement by the Member or its Members List or its guests or invitees or its pets, or from the acts or omissions of the Member or Members List or such guests or invitees or pets. The Member is responsible for the actions of or the damages caused by all persons and pets that the Member, Members List, or their guests invite to enter into the building.

10. Technology Release. The Member acknowledges that it may be necessary to install certain software onto its computers and/or other electronic devices in order to utilize all of the services or functionalities available at the Facility. The Member agrees that District and its affiliates are not responsible for any damage to the Member’s computers or other electronic devices relating to such software or any technical support provided by District or its affiliates, and that the Member assumes any liability in the event that such software interferes or otherwise adversely affects such computers or other electronic devices. District and its affiliates expressly disclaim any verbal or written warranties, express or implied, with respect to such software or any technical support provided to the Member.

11. Not a Lease. Notwithstanding anything to the contrary elsewhere in this Agreement, District and the Member agree that this Agreement does not create a landlord-tenant relationship (nor does such a relationship otherwise exist), and this Agreement shall not in any way be construed as to grant the Member any title, easement, lien, possession or related rights in the Facility, District’s business or anything contained in the Facility. This Agreement does not create a tenancy interest, leasehold estate or other real property interest. This Agreement shall not be construed to create a fiduciary or agency relationship, partnership or joint venture. Both parties agree not to misrepresent the relationship.

12. Modifications to Agreement. The Member acknowledges that from time to time, District may modify or supplement the terms and conditions of this Agreement, and will send notice of such to Member via email to Member’s email address set forth in the Membership Details. Any such changes will become effective when such changes are sent to Member or on such later date as may be specified by District. The up to date terms and conditions will be available on the Member Portal. Unless the Member terminates this Agreement within thirty (30) days of receipt of such notice, the Member shall be deemed to have accepted and agreed to such modified or supplemented terms and conditions. The continued use of the Facility by the Member shall constitute acceptance of the modified or supplemented terms and conditions. Except as set forth above, this Agreement may not be modified, except in a writing executed by the parties.

13. Pets. If the office space is in a building designated by District to be one in which pets are permitted, and if any Member plans on regularly bringing a pet into the office space, we may require this Member to produce proof of vaccination for such pet in a form satisfactory to us. All pets should remain inside the office space unless accompanied by a Member. If any Member brings a pet into the building, it will be responsible for any injury caused by this pet to other members or guests or to the property of the foregoing. Neither District nor its employees will be responsible for any injury to such pets. We reserve the right to restrict any Member’s right to bring a pet into the building.

14. Miscellaneous. (a) This Agreement is governed by the laws of the State of New York, without effect to any principles of conflicts of laws. Any action or proceeding relating to this Agreement shall be litigated in courts located in New York, New York. The Member irrevocably agrees to waive any right to a trial by jury in any such action or proceeding. (b) Neither party shall be deemed by any act or omission to have waived any of its rights or remedies hereunder unless such waiver is in writing and signed by the waiving party. (c) This Agreement is subject and subordinate to District’s lease with its landlord, and to any other agreements to which such lease is subject or subordinate. (d) Each provision of this Agreement shall be deemed severable, and to the extent that any provision of this Agreement is prohibited or unenforceable, this Agreement shall be deemed amended to the smallest degree possible in order to make the Agreement effective under applicable law. (e) Any and all notices under this Agreement may be given via e-mail, and will be effective on the first business day after being sent. (f) In any action, suit or proceeding to interpret, enforce or rescind this Agreement, the prevailing party is entitled to recover its reasonable attorneys’ fees and expenses. (g) The Member may not transfer or otherwise assign any of its rights or obligations under this Agreement without the prior written consent of District. (h) Any proceeding to resolve or litigate any dispute in any forum will be conducted solely on an individual basis. Neither the Member nor District will seek to have any dispute heard as a class action or in any other proceeding in which any party acts or proposes to act in a representative capacity. (i) Neither party is liable for, and will not be considered in default or breach of this agreement on account of, any delay or failure to perform as required by this agreement(with the exception of any obligations on the Members part to pay any sum of money due to District under this agreement for services rendered) as a result of any causes or conditions that are beyond such party’s reasonable control and which such party is unable to overcome by the exercise of reasonable diligence, provided that the affected party will use best efforts to resume normal performance. (j) All provisions of this agreement reasonably expected to survive the termination of this agreement will do so.'
			],
		];

		foreach ($textblocks as $textblock)
		{
			App\Textblock::firstOrCreate($textblock + ['workspace_id' => getenv('DEFAULT_WORKSPACE_ID')]);
		}
	}
}
